DOCUMENT_FORMAT_SETTINGS = {"formats": ["jpg",
                                        "jpeg"],
                            "min_length": 1000,
                            "max_length": 2000,
                            "recommended_length": 1200}

PDF417_FORMAT_SETTINGS = {"formats": ["jpg",
                                      "jpeg"],
                          "min_length": 469,
                          "max_length": 916,
                          "min_height": 230,
                          "max_height": 230}

SELFIE_FORMAT_SETTINGS = {"formats": ["jpg",
                                      "jpeg"],
                          "min_length": 600,
                          "max_length": 600,
                          "min_height": 720,
                          "max_height": 720}

SELFIE_TYPE_FORMATS = ['SN', 'SS', 'SCE', 'SBL', 'SBR']

APPLICATION_VERSION = "1.0.0"

STATUS_CODES = {901: 'NEW_OPERATION_OK',
                903: 'END_OPERATION_OK',
                904: 'END_OPERATION_FAIL',
                905: 'END_OPERATION_EMPTY_FAIL',
                1905: 'OPERATION_END_BARCODE_DOESNT_BELONG',
                1906: 'OPERATION_END_OCR_DOESNT_BELONG',
                1907: 'OPERATION_END_FRONT_BACK_NOT_BELONG',
                906: 'CANCEL_OPERATION_OK',
                908: 'STATUS_OPERATION_OK',
                909: 'ADD_FRONT_OK',
                911: 'FRONT_ALREADY_EXIST',
                912: 'ADD_BACK_OK',
                914: 'BACK_ALREADY_EXIST',
                915: 'ADD_OCR_OK',
                916: 'ADD_OCR_FAIL',
                920: 'ADD_BARCODE_OK',
                921: 'ADD_BARCODE_FAIL',
                925: 'ADD_ANOMALIES_OK',
                926: 'ADD_ANOMALIES_FAIL',
                932: 'ADD_SELFIES_OK',
                935: 'SCORE_EMPTY_FRONT',
                936: 'SCORE_EMPTY_SELFIE',
                937: 'SCORE_SUCCESS',
                952: 'OPERATION_NOT_EXIST',
                953: 'OPERATION_DOESNT_BELONG',
                954: 'OPERATION_DISABLED',
                960: 'IMAGE_NOT_VALID',
                963: 'ANALYZE_DOCUMENT_OK',
                964: 'ANALYZE_DOCUMENT_FAIL',
                965: 'QRCODE_OK',
                966: 'QRCODE_FAILED',
                967: 'END_OPERATION_BARCODE_ORDER_EMPTY',
                970: 'OPERATION_ENDPOINT_CREATE_OBJECT_FAILED',
                971: 'OPERATION_ENDPOINT_BUSINESS_POST_FAILED',
                972: 'FACE_ENDPOINT_CREATE_OBJECT_FAILED',
                973: 'FACE_ENDPOINT_BUSINESS_POST_FAILED',
                981: 'APIKEY_REST_FAILED',
                990: 'END_OPERATION_PERSON_PARSE_FAIL',
                1000: 'INCORRECT_PARAMETERS',
                1003: 'LOGIN_FAIL',
                1006: 'LOGIN_FAIL_CROSSCHECK',
                1010: 'SAVE_IMAGE_TO_STORAGE_FAIL',
                1011: 'LOAD_IMAGE_FROM_STORAGE_FAIL',
                1013: 'ENCRYPTION_FAIL',
                2001: 'FACE_NOT_FOUND',
                2003: 'FACE_COMPARE_OK',
                2005: 'FACE_COMPARE_FAIL',
                2006: 'FACE_SERVICE_FAIL',
                2023: 'FACE_IMAGE_BACKGROUND_ICAO_FAIL',
                2024: 'FACE_IMAGE_ANTISPOOFING_FAIL',
                2025: 'FACE_IMAGE_MONOCHROMATIC_BALANCE_FAIL',
                2027: 'FACE_IMAGE_BACKGROUND_CROSSCHECK_FAIL',
                2028: 'FACE_IMAGE_SCREEN_PLOT_FAIL',
                2029: 'FACE_IMAGE_SCREEN_SWEEP_FAIL',
                2030: 'FACE_IMAGE_FLASHLIGHT_SPOT_FAIL',
                2031: 'FACE_IMAGE_LINES_DETECTION_FAIL',
                3002: 'REGISTER_FAIL',
                3003: 'REGISTER_FAIL_CROSSCHECK',
                5001: 'BARCODE_SCAN_OK',
                5002: 'BARCODE_SCAN_NOT_DETECTED',
                9100: 'IMAGE_SANITIZATION_FAILURE',
                9200: 'BUSINESS_CONFIGURATION_EMPTY',
                9202: 'BUSINESS_CONFIGURATION_SCORE_ONBOARDING_EMPTY',
                9204: 'BUSINESS_CONFIGURATION_SCORE_FACE_EMPTY',
                9206: 'BUSINESS_CONFIGURATION_URL_ENDPOINT_PACKAGE_ONE_EMPTY',
                9207: 'BUSINESS_CONFIGURATION_URL_ENDPOINT_PACKAGE_TWO_EMPTY',
                9209: 'BUSINESS_CONFIGURATION_APIKEY_ENDPOINT_PACKAGE_ONE_EMPTY',
                9210: 'BUSINESS_CONFIGURATION_APIKEY_ENDPOINT_PACKAGE_TWO_EMPTY',
                9212: 'BUSINESS_CONFIGURATION_ENDPOINT_PACKAGE_ONE_OK',
                9213: 'BUSINESS_CONFIGURATION_ENDPOINT_PACKAGE_TWO_OK',
                9220: 'INFORMATION_RENAPER_FAILED',
                9221: 'INFORMATION_RENAPER_SAVE_FAIL',
                10001: 'RENAPER_OK_EXITO'}
